'Added-BDD-test-for-PUT'
nyu-delta-squad-s17/recommendation-service pull request #130
Opened 2017-04-18 02:48 UTC by rohithreddy1

2017-04-18 19:10 UTC, sadam0930 requested changes

2017-04-18 19:10 UTC, sadam0930 commented on features/recommendations.feature
> +	Then I should see "8"
I feel like there should be a step to visit the homepage to verify that the update is persisted.

2017-04-19 18:22 UTC, rohithreddy1 commented on features/recommendations.feature
> +	Then I should see "8"
@sadam0930 I agree. I will add the step.

2017-04-20 22:57 UTC, sadam0930 approved these changes

2017-04-20 22:57 UTC, merged